# Generated by Django 4.1.2 on 2022-11-14 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='tilte',
            field=models.CharField(default='', max_length=50),
        ),
    ]
